version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=prueba_tecnica
      - DATABASE_HOST=127.0.01
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - '5432:5432'
    volumes:
      - /home/pachiracledev/postgres-prueba:/var/lib/postgresql/data

  api-prod:
    container_name: nestjs_api_prod
    image: nestjs-api-prod
    environment:
      - JWT_SECRET=LwuMN3UQDyKEzPedomk0tXAgVHhpjFiW
      - JWT_REFRESH_SECRET=QDyKEzPedomk0tXAgVHhpjFiWLwuMN3U
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USERNAME=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=prueba_tecnica
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    depends_on:
      - postgres

networks:
  shared-network:
